### ISSUE TITLE
Bullet Chart - Not possible to configure target markers

### ISSUE THREAD

**Issue by StreamlineConsultancy** [okviz/free-visuals#117]
I have created a Power BI report with the Bullet Chart of OKViz. I added 2 measures in the Targets-field. I would like to configure the color and the shape of each target marker, but I an not able to adjust this in the Format-menu of the visual. In other reports I can adjust this for each target marker. 

![image](https://user-images.githubusercontent.com/62761966/77778474-52152200-7051-11ea-80be-06d9600742aa.png)

**Comment by danieleperilli** [comment]
At the moment, it is not possible. We will evaluate to introduce the feature in the next updates.

**Comment by stugr** [comment]
Being able to select different colours for each target marker would be super useful

**Comment by dkernen** [comment]
I have the same issues.  On the download from OKVIZ, I can see that the target marker shapes are configurable, but in my workspace, they are not.  They look the same as the screenshot above.  My targets are based on a different "goals" table rather than a multiplier of the "sales" table as shown in the demo download.  I am using 2.2.8.

**Comment by danieleperilli** [comment]
Closed since we moved issues/suggestions for Bullet Chart to a dedicated repo: https://github.com/okviz/bullet-chart-issues 
Feel free to reopen it there.
