### ISSUE TITLE
Card with States - summing the cumulative weekly goal 

### ISSUE THREAD

**Issue by csolanky** [okviz/free-visuals#135]
The value in Target is getting summarized. 
The visual was working great till I upgraded to the latest.  The states got all messed up with the new version.
I am emailing the pbix. 
![image](https://user-images.githubusercontent.com/11858680/81326490-8a038200-905f-11ea-832b-35a0548a46bf.png)

**Comment by marcosqlbi** [comment]
In the meantime you can downgrade to the previous version following these instructions: 
https://okviz.com/blog/how-to-downgrade-a-visual-imported-from-the-appsource-marketplace/

**Comment by csolanky** [comment]
Thanks. Downgrading worked and the data is as expected. Will wait to hear back.

**Comment by danieleperilli** [comment]
The goal is summed because you chose to see the sums of values in the data label. I know, the previous version didn't work this way, but it's more logical now. 

![image](https://user-images.githubusercontent.com/9072177/81373798-dc937b80-90fd-11ea-95f4-d0e6c2bcd928.png)

About the states: I think there was a bug in the previous version, because looking at the data the conditions are properly applied. 

![image](https://user-images.githubusercontent.com/9072177/81374535-c38bca00-90ff-11ea-84e0-96bd53a65c46.png)
(the comparison operator is < )

**Comment by Tanako123** [comment]
Like you said it works on the old visual the goal wont get summed. But is there a workaround for it? in dax maybe or?
I need some function in 1.6 that why i cannot downgrade

thanks in advance

**Comment by danieleperilli** [comment]
You can downgrade using a previous version from our website. Please note that private versions are not certified and will not updated in the future.

**Comment by Tanako123** [comment]
Thanks for your response! the problem is that i dont want to downgrade because i need some of the function from the new version. Is there any other way?
