### ISSUE TITLE
Bullet Chart - Data Labels

### ISSUE THREAD

**Issue by Iggypup** [okviz/free-visuals#15]
Any chance we could have data labels for all aspects of the chart?

**Comment by danieleperilli** [comment]
We will consider your suggestion for the next update. Unfortunately, we don't have any release date, yet.

**Comment by herkyjerky** [comment]
Appreciate this visual and I hope development on this isn't dead. 
My use case for adding labels to the comparison bar (and target) as well 'value' because my scenario has a different target for each item (actual count vs target count by group). imagine something like actual voters vs registered voters by state.  

i would appreciate being able additional independent options to have the 'value' be next to base, inside end, centered on end, outside end and target and comparison element values having all options but "next to base."

**Comment by danieleperilli** [comment]
Closed since we moved issues/suggestions for Bullet Chart to a dedicated repo: https://github.com/okviz/bullet-chart-issues 
Feel free to reopen it there.
