### ISSUE TITLE
Card with states - Value not being displayed if it is blank

### ISSUE THREAD

**Issue by infused-kim** [okviz/free-visuals#222]
Hi,

FIrst of all, happy holidays and thank you for creating such a crucial addition for Power BI.

**Describe the issue**
When displaying multiple values in the visual, blank values are skipped completely and not displayed at all. I understand this may be the desired behavior in some instances, but I think in many instances it is not.

For example, I am building a custom KPI row with multiple values and custom titles (for design purposes). But if one of the KPIs is blank, the entire row shifts and the titles don't add up anymore.

I also think that displaying (Blank) or 0 for measures that don't have a value is a better default, since knowing that a metric is 0 (or blank) is in itself an important piece of information.

I know this can be worked around by creating a measure that checks if the value is blank and then returns 0, but this would double the measures in the dataset. Plus it would make it much harder for end-users to use, since now they have to decide which measure to use when.

I propose to add a dropdown option `How to handle blanks` and let the user select the options:
- Hide (Default to maintain backwards compatibility)
- Show (blank)
- Show 0

**To reproduce**
- Add the card with states visual
- Add several measures
- Make one of the measures blank
- Watch the measure disappear

**Affected environment**
 - Power BI Desktop December 2020
 - Did not test any other environments

**REQUIRED: Repro file**
Can be downloaded here:
https://1drv.ms/u/s!AiPkjSqghF1xhOd-wsQWE7X_dEvLVA?e=KjuhNI

Select the second tab `Blanks disappearing`.

**Screenshots**
Attached below...
![Microsoft Remote Desktop_2020-12-26 19-01-22@2x](https://user-images.githubusercontent.com/7404004/103154028-689e0480-47ae-11eb-9d70-2bc32290993a.jpg)

**Comment by GethinUCL** [comment]
We have exactly this issue and the solution above would be fantastic. 
I'd add that this behaviour also happens when a selection is made in the report page that makes a measure blank.
Our template design includes a header ribbon made of multiple cards and cards disappear if you make a selection that results in any of the measures returning blank, this impacts the design of the report and means a different measure appears exactly where a previous measure was shown which could easily confuse users.

Default
![image](https://user-images.githubusercontent.com/56540495/105469769-a187a700-5c90-11eb-83d0-871791e1790e.png)

When some measures are blank due to selections
![image](https://user-images.githubusercontent.com/56540495/105470108-0d6a0f80-5c91-11eb-8e5b-41d2da20b431.png)

A final point to note - the remaining visible cards still get auto sized as if the (Blank) measures were showing. Whereas if I removed those measures from the visualisation completely, the others stretch to fill the visualisation size.

![image](https://user-images.githubusercontent.com/56540495/105470588-a731bc80-5c91-11eb-99ae-09c6061ef5aa.png)

Thanks as always for all your work and contribution to the community.

**Comment by chrisbilsoe** [comment]
Any update on this issue?

**Comment by riccard0russ0** [comment]
We have temporarily suspended the development of new features and addressing bugs that aren't related to security. This decision is based on the fact that the new Power BI built-in Cards supports almost all Card with States functionalities. We will reconsider this decision if our plans change.
