### ISSUE TITLE
Smart Filter - Labels have disappeared since release of "Pro"

### ISSUE THREAD

**Issue by SMHolck** [okviz/free-visuals#24]
I love the Filter.  It is a bit buggy, but we've figured out workarounds for most of the problem and we like the search functionality.  I've been using this on reports, but yesterday my users noticed that there were no longer labels for the Smart Filters on their reports.  When I investigated, I discovered the reports are showing a notice that because the reports have themes on them, we must upgrade to Pro.  

![SmarFilterByOKViz_LabelsMissing](https://user-images.githubusercontent.com/11869380/59951121-2bc4b500-9435-11e9-8c56-38aed8f06cf9.png)

I downloaded the June 2019 PBI desktop, opened the report, and discovered the default is to have the "Labels & Placement" set to Off.  This is forcing me to have to update every report we have deployed.  While this does provide the same level of functionality as before the update and thus appears to be in keeping with the certified visual policy, this does not engender goodwill for future purposes.  I'm now afraid to use your visuals lest I end up having to update 100s or thousands of reports if you make a change.  Was this intentional?  Or just a QA oversight?

**Comment by danieleperilli** [comment]
Unfortunately, you are right, we accidentally change the internal position of that option and this caused incompatibility with existing instances.  I'm sorry for that, you have to manually re-enabled it, because also if we made a fix today it will take 3/5 weeks to be released in the marketplace (Microsoft review time takes a lot). 
About the alert: you can disable it by changing the _Missing features alerts_ toggle in the Premium options panel.
