### ISSUE TITLE
Synoptic for Power BI- Can not edit previous made map

### ISSUE THREAD

**Issue by Elcuatro** [okviz/free-visuals#244]
The name of areas have underscore characters in my map and when trying to edit  previous saved map in Synoptic web tool, it removes all underscore characters from areas names make it very difficult to edit map

**Comment by ksepowerbi** [comment]
I have a similar issue with the underscore in the ''Area name (to bind)'' field. My data has underscores in the area name field ( such as DEF_1 ), and in order to match the map with the data, the underscores should be in the map field as well. However, as Elcuatro mentions, once the map is saved in the web tool, the underscores are removed from the map. In Power BI the underscore is replaced by a blank space " " and thus the data is not linked to the map.

Is this issue fimiliar with the developers? And any idea when this will be adressed?

Thanks in advance!

**Comment by riccard0russ0** [comment]
We would like to clarify that the current version of the Synoptic Designer is mainly a proof of concept, and it might not encompass all the functionalities needed, especially for complex tasks. SVG file editing is quite limited at the moment and you should use a grapich designer such as Inkscape (free) or Illustator to modify it.

In addition, we wanted to let you know that we are actively working on a **New Premium Version** of Synoptic Panel, slated for release in the coming months. This new version aims to address various bugs and integrate new functionalities that would enhance the user experience significantly. 

**In our roadmap we also have the implementation of a new advanced editor that will facilitate creation, editing and data-binding for SVG maps**. To streamline the process of reporting bugs or suggesting new features, we have established a dedicated repository. We encourage you to visit and contribute to this repository, as it will serve as a centralized platform where we will be actively monitoring and considering all suggestions and report for the new Synoptic Panel.

[New repository: synoptic-panel-issues](https://github.com/okviz/synoptic-panel-issues)
