### ISSUE TITLE
Synoptic Panel - Saturation coloring issue when all values are zero 

### ISSUE THREAD

**Issue by reileybergin** [okviz/free-visuals#270]
**Describe the issue**
I am using the synoptic panel to map regions of the body that have been injured.

![image](https://user-images.githubusercontent.com/25494043/118559705-54937900-b736-11eb-91aa-69d112fe8fd8.png)

The issue I have run into is that when a person who has no injuries at all (total = 0) is selected the synoptic panel is carrying over the saturation from the previous selection.

![image](https://user-images.githubusercontent.com/25494043/118560014-d71c3880-b736-11eb-92b1-db2cb863930e.png)

**To reproduce**

1. Select the name Bill or Steve from the filter (both contain at least one injury)
2. Select the name Sam from the filter (has zero total injuries)

**Affected environment**
 - Power BI Desktop (include the version: E.g.: April 2020)
 - Power BI service

**REQUIRED: Repro file**
[satuation_issue.zip](https://github.com/okviz/free-visuals/files/6497038/satuation_issue.zip)

**Comment by mah65** [comment]
I am encountering similar issues. Plus inconsistent and wrong coloring saturations.

**Comment by JIBG4** [comment]
I have the same issue when values are (Blank)

I am using the Synoptic Panel (incredible useful visual!) to measure color coded scale of percentages set in the SP visual with States;

1.	Every is Blue all sections are above 91%
2.	If I click on Block-2 “H” section, all the other sections turn light blue and if I mouseover I can see that section “D” is 95%.
3.	BUT, if I use an slicer to filter section “H”, the rest of the section turn light RED, If I mouse over I can see that the section “D” is blank…SO

How can I set a default color for “Blank” values?  color Red is not appropriate to be the default color since this is the most use color when measuring performance that been one of the main purposes of this visual. I tried changing the visual “Default Color” property to different colors with no luck, is this a bug or there is a way to changing it?
![Post](https://user-images.githubusercontent.com/88497401/128398054-6fa115ef-b32d-4d6e-91fe-23dcfb9be47d.png)

**Comment by riccard0russ0** [comment]
Thank you for reaching out and sharing your feedback on Synoptic Panel. We are committed to continually improving our products, and your input is incredibly valuable in helping us identify areas for enhancement and development.

We wanted to let you know that we are actively working on a **New Premium Version** of the visual, slated for release in the coming months. This new version aims to address various bugs and integrate new functionalities that would enhance the user experience significantly.
 
**Your issue will be solved in this new version**.

The current free version will not receive updates in the near future, except for security issues.
To streamline the process of suggesting new features for the new version, we have established a dedicated repository. We encourage you to visit and contribute to this repository, as it will serve as a centralized platform where we will be actively monitoring and considering all suggestions and report for the new Synoptic Panel.

[New repository: synoptic-panel-issues](https://github.com/okviz/synoptic-panel-issues)
