### ISSUE TITLE
Smart Filter - Not Sorting values

### ISSUE THREAD

**Issue by nickhernigle** [okviz/free-visuals#315]
The Smart filter is not sorting the information in the filter properly. 

I couldn't find a way to have the information sorted from A-Z in the customizer in Power BI.

**Comment by cwollett** [comment]
I believe this may be related to the above. I have a list of room numbers that consistently places values starting with a 0 at the end of the list. It's as though it's sorting (1-9,0) instead of (0-9).

This is a text field, not fully numeric (because there might be 120A and 120B). However, when I sort this within the table view in Power BI, it sorts as expected - if the first character is 0 it appears before something where the first character is 1.

Screenshot of bad sort:
![image](https://user-images.githubusercontent.com/17076002/158894319-3e80b2ea-fda6-45f9-9d57-7e507d6a8836.png)

**Comment by danieleperilli** [comment]
Closed since not sample has been provided. However, I suggest you try Smart Filter Pro, which introduced a lot of new features and enhanced behaviors.
