### ISSUE TITLE
Smart Filter - Dropdown behind all items in Web Version

### ISSUE THREAD

**Issue by JoshSJoshS** [okviz/free-visuals#32]
Previously when a user would select the drop down it would be in front of everything, regardless of the sorted location of the actual visualization.  Now, when viewing on the web, it is behind anything and everything.  I don't want to move it up in the Selection Layer Order because then the transparent space for the dropdown covers other components of the PBI report.

![Drop Down Hidden](https://user-images.githubusercontent.com/53184420/61641176-a9febc00-ac6c-11e9-837f-842b78450a8c.png)

**Comment by danieleperilli** [comment]
I just tried in Power BI desktop and it works as expected (Smart Filter under another chart - dropdown list appears over the chart). Are you using a specific browser? Which one? Can you try in the desktop app?

**Comment by JoshSJoshS** [comment]
Desktop App works fine, goes on top.  It was the web version that would not.  Google Chrome.

**Comment by danieleperilli** [comment]
For me it happens only when you move the cursor outside the visual canvas. I'm not sure is something related to the visual. Anyway is still usable, because when you go back to the visual's boundaries, it get the focus again.

**Comment by JoshSJoshS** [comment]
How do I send a PBIX?

**Comment by danieleperilli** [comment]
support@okviz.com

**Comment by JoshSJoshS** [comment]
I sent an email yesterday, did you receive?

**Comment by danieleperilli** [comment]
Yes, not checked yet.

**Comment by JoshSJoshS** [comment]
No problem. Just checking!

**Comment by danieleperilli** [comment]
I just checked your file and found you are right. Something changed in the behavior of the visual in Power BI online (I also noticed that this happens with to the Pro Version). I've submitted the issue to Microsoft, because is certainly caused by a change in the platform. I will update this issue when they reply me.

**Comment by JoshSJoshS** [comment]
Ah, ok, that will happen.  Glad steps are being taken to correct it.  Thanks!

**Comment by amudalalalith** [comment]
Hi,
I also face the same problem with the filter, can you please let us know when you find an update.

**Comment by danieleperilli** [comment]
Yes, we are waiting for the support team response. I can't say how much time will take. Probably, it is something related to the end-of-month update they just announced.

**Comment by danieleperilli** [comment]
We are still waiting for a confirmation from Microsoft.
Because this change is affecting your report, we kindly ask you to open a support ticket going to [https://powerbi.microsoft.com/en-us/support/](https://powerbi.microsoft.com/en-us/support/) and clicking on **CREATE SUPPORT TICKET** at the bottom of the page.

**This action will raise the priority of the report we already open, which otherwise could not escalate properly in terms of priority.**

**Comment by danieleperilli** [comment]
Microsoft reported us that the issue has been fixed. I just tested it and it works as expected now.

**Comment by axrand** [comment]
Looks like the issue is back. Can anyone else confirm?
