### ISSUE TITLE
Synoptic Panel - Map remote uri issue

### ISSUE THREAD

**Issue by dan-ong** [okviz/free-visuals#335]
Using.svg map uri generated by amazon s3 bucket presigned url within Synoptic-Panel 'Maps' field results in an error message stating that 'The provided image is not an svg image file'. However, .svg images show correctly within table and download correctly when pasted into browser. Possibly caused by:
- url not containing a .svg suffix
- s3 bucket link is a direct download link

Would be great if someone could confirm if the issue is caused by Synoptic-Panel using a check for a '.svg' suffix, or if this issue has been encountered previously?
![image](https://user-images.githubusercontent.com/92493469/177505794-007ff8ec-674d-482c-8e3d-8df374d51ea5.png)

Unfortunately, I am unable to provide Power BI file due to commercial privacy issues.

**Comment by danieleperilli** [comment]
Sorry for the late reply: yes, it was because the URL does not end with ".svg".

BTW: We wanted to let you know that we are actively working on a **New Premium Version** of the visual, slated for release in the coming months. This new version aims to address various bugs and integrate new functionalities that would enhance the user experience  significantly.  **Your issue will be solved in this new version**. The current free version will not receive updates in the near future, except for security issues. To streamline the process of suggesting new features for the new version, we have established a dedicated repository. We encourage you to visit and contribute to this repository, as it will serve as a centralized platform where we will be actively monitoring  and considering all suggestions and report for the new Synoptic Panel. 

[New repository: synoptic-panel-issues](https://github.com/okviz/synoptic-panel-issues)
