### ISSUE TITLE
Synoptic Panel - tooltips  not visible in web

### ISSUE THREAD

**Issue by JorgeArranzVillegas** [okviz/free-visuals#372]
### Visual

Synoptic Panel

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The tooltips of a Synoptic Panel are not visible in web. In PBI destokp they're visble, but when I upload the report they don't appear

### Power BI

Power BI service

### Power BI Version

PRO

### Sample report

[PRUEBAMAPA.zip](https://github.com/okviz/free-visuals/files/11454805/PRUEBAMAPA.zip)

**Comment by bisvillallai** [comment]
I have the exact same issue since 4 or 5 days ago, in my case works on mobile app and desktop, but stop working when publish to BI service (web).

**Comment by mrajamiesutton** [comment]
I also have the same issue! But only on 1 out of 3 reports where I use this visual. Can we please get some support on this issue?

**Comment by riccard0russ0** [comment]
This issue was closed for lack of sample report.

Anyway, we wanted to let you know that we are actively working on a new **Premium** version of the visual, slated for release in the coming months. This new version aims to address various bugs and integrate new functionalities that would enhance the user experience significantly. The current free version will not receive updates in the near future, except for security issues.
To streamline the process of suggesting new features for the new version, we have established a dedicated repository. We encourage you to visit and contribute to this repository, as it will serve as a centralized platform where we will be actively monitoring and considering all suggestions and report for the new Synoptic Panel.

[Repository link](https://github.com/okviz/synoptic-panel-issues)
