### ISSUE TITLE
Export issue on Synoptic designer tool

### ISSUE THREAD

**Issue by CandiiiiceGe** [okviz/free-visuals#386]
### Visual

Synoptic Panel

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I try to export to power bi, there is no preview image shown.
Even though I right click and save locally, there is no picture saved, only html.

![image](https://github.com/okviz/free-visuals/assets/130436388/368086a2-04b0-47ea-9326-7244132c7763)

![image](https://github.com/okviz/free-visuals/assets/130436388/2933271b-68b9-4473-9091-1018ce1ce289)

### Power BI

Power BI service

### Steps To Reproduce

1. Click EXPORT TO POWER BI
2. Preview image is not shown
3. Right Click and save locally, there is no image saved but html file

### Sample report

![image](https://github.com/okviz/free-visuals/assets/130436388/c2554fa2-3438-412b-9a99-5b9b4acc478f)

**Comment by danieleperilli** [comment]
We are not able to reproduce it. Perhaps it is caused by the browser cache. We recommend cleaning it and trying again.
Also note that this is only a proof-of-concept tool, so we do not support it directly.
You can achieve the same result using a graphics editor such as Inkspace or Illustrator, as explained here: 
https://okviz.com/blog/introducing-synoptic-panel-v1-4/#use-editor
