### ISSUE TITLE
Limite de filas en Samart Filter

### ISSUE THREAD

**Issue by OSSA-Praxis** [okviz/free-visuals#43]
Hello Good afternoon,
I recently acquired the Visual Smart Filter Pro to test it, since in the specifications it said that it has no limit of rows and when testing it it seems to me the following error with the legend that says. "The result set of a query from an external data source exceeded the maximum allowed size of 1000000 rows", 
I would appreciate your support in solving this detail 
Best regards 
Arian Osorio
![error](https://user-images.githubusercontent.com/53799045/62499583-de17c800-b7a8-11e9-868f-7f29a79fe94f.PNG)

**Comment by okviz** [comment]
You are seeing an error that is not specific of Smart Filter Pro, it is a limit of a DirectQuery connection.
If you replace Smart Filter Pro with another visual, you should see the same error.
This is explained in the Microsoft documentation:
https://docs.microsoft.com/en-us/power-bi/desktop-use-directquery
(see Limitations of DirectQuery section).

A more detailed explanation of this limit is included in this white paper (it is valid also for Power BI):
https://www.sqlbi.com/whitepapers/directquery-in-analysis-services-2016/

My suggestion is to fix the problem in the model and in your calculation so that you do not hit that limit, then you can use any visualization in your report, including Smart Filter Pro.

**Comment by OSSA-Praxis** [comment]
Pero si el requerimiento es consultar toda la información, como puedo darle la vuelta o ver mis datos y empezar a segmentar estos datos,
Actualmente la gente consulta toda la información y va segmentado,  pero nos encontramos, que desde los filtros no podemos empezar a segmentar los datos.
Se esta haciendo una migración de Cognos a Power BI pero con esta limitación esto nos detiene y nos pone en un dilema muy grande.

Agradecería su amable apoyo.
Saludos cordiales
Arian Osorio

**Comment by marcosqlbi** [comment]
Arian, please read the whitepaper I provided - the message you see could be a problem of the internal query generated by DirectQuery and it could appear even in case you do not have that amount of data to display. 
Do you have the same issue importing the data, or is this limited to DirectQuery?
You have a number of limitations using DirectQuery, the best way to use Power BI is by importing data in the model.
However, this is an issue not related to the component, you should see the same behavior using any other visualization.
