### ISSUE TITLE
Card with States: Dynamic Text from Measure for Category / States label

### ISSUE THREAD

**Issue by schuffa** [okviz/free-visuals#46]
Hello, it's likey rather an idea than an issue: Since Power BI released in Apr 2019 the possibility of measure based / dynamic chart titels (https://powerbi.microsoft.com/en-us/blog/power-bi-desktop-april-2019-feature-summary/#dynamicTitles) I'm wondering if it would be possible to add this feature as well within your visual text fields as to Category Label / Custom & State messages?

**Comment by danieleperilli** [comment]
Unfortunately, there isn't any API to do that in other fields. Anyway, we made some changes in the latest version (currently under review by Microsoft) in order to make the category label more dynamic.
<img width="455" alt="Development_-_Bullet_Chart_-_Power_BI" src="https://user-images.githubusercontent.com/9072177/62854930-13fd0500-bcf1-11e9-9154-0d6ace68d909.png">
