### ISSUE TITLE
Synoptic Panel - How can I make the black text underneath the SVG data areas render as black? 

### ISSUE THREAD

**Issue by Mike-Honey** [okviz/free-visuals#53]
In my SVG, the areas have black text underneath them from a lower layer. This text looks black in the online Synoptic Designer.  However when rendered in Power BI, the text appears faded gray, so it's not very readable.  

My text sometimes overlaps several SVG areas, so Data Labels aren't an option. How can I make the text appear Black? 

Sample PBIX file and SVG are attached:

[Synoptic Panel questions 2019-08-25.zip](https://github.com/okviz/free-visuals/files/3538026/Synoptic.Panel.questions.2019-08-25.zip)

**Comment by danieleperilli** [comment]
You used a bitmap image with hardcoded text without transparency: this way, the space that appears empty is filled with white color. If you put this image in front of the other shapes (you can do it with a graphic editor or manually by opening the SVG map in the notepad), all the areas will be covered by the white space. You can try to make the white space transparent,  but usually this action doesn't produce a good-quality result. The best way to solve your issue is to redraw a vector diagram with an advanced graphic editor such as Inkspace or Adobe Illustrator.

**Comment by Mike-Honey** [comment]
Thanks for your guidance Daniele - much appreciated.
